.gitignore
Gradle temporary files, Eclipse files and IntelliJ files ignored
=> Gradle files ignore and ide settings

build.gradle, src/main/resources/application-it.properties, src/test/java/br/com/fakebank/PessoaEndpointIT.java, src/test/resources/br/com/fakebank/PessoaEndpointIT.sql, src/test/resources/h2/db/migration/V1__create_table_pessoa.sql
Criada a classe PessoaEndpointIT para realizar testes de integração contra o endpoint /pessoas.
Para a realização destes testes, foram adicionadas dependências com o H2 e o Flyway para suportar banco de dados na memória durante a execução dos mesmos.
=> Criada classe para testes de integração do endpoint Pessoa

.classpath, src/main/java/br/com/fakebank/domain/Gerente.java, src/main/java/br/com/fakebank/domain/commands/ClientePessoaJuridicaEdicaoCommand.java, src/main/java/br/com/fakebank/domain/commands/ClientePessoaJuridicaInclusaoCommand.java, src/main/java/br/com/fakebank/domain/commands/GerenteEdicaoCommand.java, src/main/java/br/com/fakebank/domain/commands/GerenteInclusaoCommand.java
Adição de arquivos que foram removidos em outro commit.
=> Arquivos que faltavam no projeto

src/main/java/br/com/fakebank/repository/ContaRepository.java, src/main/java/br/com/fakebank/service/ContaService.java
Criacao do Repository e do Service da entidade Conta.
=> Commit da criação do Repository e do Service.

src/main/java/br/com/fakebank/endpoint/MovimentacaoEndpoint.java, src/main/java/br/com/fakebank/repository/MovimentacaoRepository.java, src/main/java/br/com/fakebank/service/MovimentacaoService.java
Criado o Repository e Service para as Movimentações.
=> adicionado o Service e Repository para a Movimentacao

src/main/java/br/com/fakebank/domain/ClienteTelefone.java, src/main/java/br/com/fakebank/endpoint/ContaEndPoint.java, src/main/java/br/com/fakebank/repository/ContaRepository.java, src/main/java/br/com/fakebank/representations/ContaRepresentation.java, src/main/java/br/com/fakebank/service/ContaService.java
inclusao endpoit inicial e primeira consulta
=> Conta end point branch

src/main/java/br/com/fakebank/domain/Gerente.java, src/main/java/br/com/fakebank/service/GerenteService.java
- Finalizando classe GerenteService
=> finalizando gerente-service

src/main/java/br/com/fakebank/domain/specifications/ContaSpecifications.java, src/main/java/br/com/fakebank/service/ContaService.java
Adicionados novos metodos de salvar.
=> Evolucao conta service e specification

src/main/java/br/com/fakebank/domain/Conta.java, src/main/java/br/com/fakebank/domain/commands/ContaCorrenteEdicaoCommand.java, src/main/java/br/com/fakebank/domain/commands/ContaCorrenteInclusaoCommand.java, src/main/java/br/com/fakebank/domain/commands/ContaPoupancaEdicaoCommand.java, src/main/java/br/com/fakebank/domain/commands/ContaPoupancaInclusaoCommand.java, src/main/java/br/com/fakebank/domain/commands/ContaSalarioEdicaoCommand.java, src/main/java/br/com/fakebank/domain/commands/ContaSalarioInclusaoCommand.java
Alterações de código de agência e criação de classes de command de edição.
=> Exemplo aquino

src/main/java/br/com/fakebank/customValidators/ContaForeignKeyClientePrincipal.java, src/main/java/br/com/fakebank/customValidators/ContaForeignKeyClientePrincipalValidator.java, src/main/java/br/com/fakebank/customValidators/ContaForeignKeyGerente.java, src/main/java/br/com/fakebank/customValidators/ContaForeignKeyGerenteValidator.java, src/main/java/br/com/fakebank/customValidators/ContaForeignKeySituacaoConta.java, src/main/java/br/com/fakebank/customValidators/ContaForeignKeySituacaoContaValidator.java, src/main/java/br/com/fakebank/customValidators/ContaForeignKeyTipoConta.java, src/main/java/br/com/fakebank/customValidators/ContaForeignKeyTipoContaValidator.java, src/main/java/br/com/fakebank/domain/Conta.java
Inclusão dos validators para a conta.
=> Inclusão dos validators para a conta.

src/main/java/br/com/fakebank/domain/commands/ContaCorrenteEdicaoCommand.java, src/main/java/br/com/fakebank/domain/commands/ContaPoupancaEdicaoCommand.java, src/main/java/br/com/fakebank/domain/commands/ContaSalarioEdicaoCommand.java
Retirado o saldo das classes de edição de contas.
=> Retirado o saldo das classes de edição das contas.

src/main/java/br/com/fakebank/domain/Cliente.java, src/main/java/br/com/fakebank/domain/Pessoa.java, src/main/java/br/com/fakebank/domain/TipoPessoa.java, src/main/java/br/com/fakebank/domain/commands/ClientePessoaFisicaInclusaoCommand.java, src/main/java/br/com/fakebank/domain/converters/TipoPessoaConverter.java
Novas Modificacoes nas classes de comando Cliente PJ e PF
=> Novas Modificacoes nas classes de comando Cliente PJ e PF

src/main/java/br/com/fakebank/endpoint/ClienteTelefoneEndpoint.java, src/main/java/br/com/fakebank/representations/ClienteTelefoneRepresentation.java, src/main/java/br/com/fakebank/service/ClienteService.java
Criação e utilização da ClienteTelefoneRepresentaion no Endpoint de telefone
=> Formata resposta do endpoint de telefone

src/main/java/br/com/fakebank/domain/ClienteTelefone.java, src/main/java/br/com/fakebank/domain/commands/ClienteTelefoneInclusaoCommand.java, src/main/java/br/com/fakebank/endpoint/ClienteTelefoneEndpoint.java, src/main/java/br/com/fakebank/service/ClienteService.java
Alteração agora é feita no domínio e nome das propriedades ajustadas.
=> Reestruturação da funcionalidade de inserir telefone

src/main/java/br/com/fakebank/domain/GerenteAgencia.java
Criando classe de domínio ClienteAgencia
=> criando domain ClienteAgencia

src/main/java/br/com/fakebank/domain/specifications/GerenteAgenciaSpecifications.java
cirando specifications de GerenteAgencia
=> cirando specifications de GerenteAgencia

src/main/java/br/com/fakebank/repository/GerenteAgenciaRepository.java
criando repoistory de gerente-agencia
=> criando repository de gerente-agencia

src/main/java/br/com/fakebank/domain/Agencia.java, src/main/java/br/com/fakebank/domain/commands/AgenciaEdicaoCommand.java
Simples implementação de alguns @Validators no Command de Edição de Agência, e acionamento do método de validação no Domínio.
Disponibilização do validate() com Command:
```java
public void validate() {
CommandValidator<AgenciaEdicaoCommand> validator =
new CommandValidator<AgenciaEdicaoCommand>();
validator.validate(this);
}
```
Acionamento da validação do Domínio
```java
public void editar(AgenciaEdicaoCommand comando){
comando.validate();
this.numero = comando.getNumero();
this.nome = comando.getNome();
}
```
=> Implementação da estrutura de validação para edição de agência

src/main/java/br/com/fakebank/repository/ContaEncerradaRepository.java
=> ajuste encerramento

.project, src/main/java/br/com/fakebank/domain/Conta.java, src/main/java/br/com/fakebank/representations/ContaCorrenteRepresentation.java, src/main/java/br/com/fakebank/representations/ContaPoupancaRepresentation.java, src/main/java/br/com/fakebank/representations/ContaRepresentation.java, src/main/java/br/com/fakebank/representations/ContaSalarioRepresentation.java, src/test/java/br/com/fakebank/PessoaEndpointIT.java
Alteracao do dominio Conta para transformar o Gerente em objeto
=> Alteracao do dominio Conta para transformar o Gerente em objeto

src/main/java/br/com/fakebank/domain/Cliente.java, src/main/java/br/com/fakebank/domain/commands/ClientePessoaJuridicaInclusaoCommand.java
=> clientepj-05

src/main/java/br/com/fakebank/domain/ContaEncerrada.java, src/main/java/br/com/fakebank/service/ContaEncerradaService.java
=> conta encerrada endpoint

src/main/java/br/com/fakebank/service/GerenteService.java
- Fix bug de retorno para consulta de gerente
#100 e #117
=> alteracao do servico de gerente

src/main/java/br/com/fakebank/domain/Conta.java, src/main/java/br/com/fakebank/representations/ContaRepresentationClientePJ.java
ajuste dominio e representation pj
=> ajuste dominio e representation pj

src/main/java/br/com/fakebank/domain/Conta.java, src/main/java/br/com/fakebank/domain/ContaEncerrada.java, src/main/java/br/com/fakebank/service/ContaEncerradaService.java
=> encerramento realizado

src/main/java/br/com/fakebank/SwaggerConfiguration.java, src/main/java/br/com/fakebank/domain/ClienteTelefone.java, src/main/java/br/com/fakebank/domain/ClienteTelefoneId.java, src/main/java/br/com/fakebank/domain/Conta.java, src/main/java/br/com/fakebank/domain/ContaEncerrada.java, src/main/java/br/com/fakebank/domain/Movimentacao.java, src/main/java/br/com/fakebank/domain/commands/ContaCorrenteInclusaoCommand.java, src/main/java/br/com/fakebank/domain/commands/ContaPoupancaInclusaoCommand.java, src/main/java/br/com/fakebank/domain/commands/ContaSalarioInclusaoCommand.java, src/main/java/br/com/fakebank/domain/validators/CommandValidator.java, src/main/java/br/com/fakebank/endpoint/ClientePessoaJuridicaEndpointV1.java, src/main/java/br/com/fakebank/endpoint/ClienteTelefoneEndpoint.java, src/main/java/br/com/fakebank/endpoint/PessoaEndpoint.java, src/main/java/br/com/fakebank/exceptions/BadRequestException.java, src/main/java/br/com/fakebank/exceptions/NotFoundException.java, src/main/java/br/com/fakebank/exceptions/RestExceptionHandler.java, src/main/java/br/com/fakebank/representations/ClienteTelefoneRepresentation.java, src/main/java/br/com/fakebank/representations/ContaRepresentationClientePF.java, src/test/java/br/com/fakebank/PessoaEndpointIT.java
Haviam warnings poluindo o código.
Não muitos ... mas foram eliminados.
=> Eliminação de warnings no código

src/main/java/br/com/fakebank/domain/ClienteTelefone.java, src/main/java/br/com/fakebank/domain/commands/ClienteTelefoneEdicaoCommand.java, src/main/java/br/com/fakebank/domain/commands/ClienteTelefoneInclusaoCommand.java, src/main/java/br/com/fakebank/endpoint/ClienteTelefoneEndpoint.java, src/main/java/br/com/fakebank/representations/ClienteTelefoneRepresentation.java
- Ajusta retorno da operação de edição
- Altera nome do atributo de tipo
=> Ajustes no endpoint de telefone

src/main/java/br/com/fakebank/domain/Conta.java, src/main/java/br/com/fakebank/domain/ContaEncerrada.java, src/main/java/br/com/fakebank/endpoint/ContaEncerradaEndpoint.java, src/main/java/br/com/fakebank/representations/ContaEncerradaRepresentation.java, src/main/java/br/com/fakebank/service/ContaEncerradaService.java
=> encerramento ajustes
